site_name: Textalytics
site_url: http://textalytics.net/

nav:
    - Home: index.md
    - Courses:
        - 115: 115.md
        - 332: 332.md
        # - 335: 335.md
        - 432: 432.md
        - 531: 531.md
        - 632: 632.md
        # - Digital Humanities: dh.md
    - Courses I Would Like to Teach:
        - Introduction to Text Analytics: c200-textanayltics.md
        - The Spread of (Mis)Information: c400-infospread.md
        - What We Think When We Think about Machine Thinking: c300-ai.md
    - Guides:
        - Accessing databases: guides/access.md
        - Chicago Author-Date Citations: guides/cad.md
        - Essentials: guides/essentials.md
        - Interview Tips: guides/interview_tips.md
        - On Notes and Notetaking: guides/noted.md
        - Paragraphs: guides/paragraphs.md
        - Says/Does: guides/says_does.md
        - Writing a Summary: guides/summaries.md
        - Recording Hardware and Software: guides/recording.md
        - Writing Help: guides/writing.md

theme:
    name: null
    custom_dir: 'julienne/'

markdown_extensions:
    - smarty
